### ISSUE TITLE
Проверить генерацию дисперсий (получаются отрицательными)

### ISSUE THREAD

**Issue by Al-xandr1** [Al-xandr1/DTNResearch#21]
Ошибка находиться в утилите SelfSimCalculator.

* Набор данных, на которых возникает ошибка: 
https://yadi.sk/d/qz5yuMo_vPsJM -> \KAIST\EXPERIMENTS\Levy\LevyHotSpotLATP_50_on_KAIST\  (waypointfiles & bounds.bnd) 

* Описание метода на странице 9 (5. BURSTY SPOT MODEL) в статье:
[Demystifying_Levy_Walk_Patterns.pdf](https://github.com/Al-xandr1/DTNResearch/files/1142784/Demystifying_Levy_Walk_Patterns.pdf)
Нужно рассматривать только часть с вычислением дисперсий (генерация - это отдельная утилита)

**Comment by expai** [comment]
Ошибка в выходных данных утилиты SelfSimCalculator возникла из-за потери точности в типе double при расчете формулы дисперсии в методе  calculateVariances, а также при переполнении типа unsigned int в цикле при возведение в степень 2.

Решение –  При расчете формулы дисперсии использование типа float128 вместо double из библиотеки boost и в цикле при возведении в степень 2 принудительное приведение типов из int к float128   

Коммиты – Подключение библиотеки 6de0bb5e1447d8de231da7845f99b0522a3a502d.
Фикс ошибки расчета  88f7b9ab241dfa69f5c55b0f21f0d2cb47e7256b

**Comment by Al-xandr1** [comment]
Смёржено в 170ecab208e59979b49737fbc4a667a85d0e069
