### ISSUE TITLE
Реализовать мобильность RealMobility 

### ISSUE THREAD

**Issue by Al-xandr1** [Al-xandr1/DTNResearch#39]
Реализовать проигрывание реальных трасс.
* Проигрывать по точкам трассы или по рассчитанным путевым точкам?
* Встроить в архитектуру существующих мобильностей
* Настроить конфигурацию запуска
* Верифицировать работоспособность

**Comment by privalov1967** [comment]
Проигрывать по точкам реальной трассы, при этом обратите внимание, что
время перехода от одной точки к другой должно быть таким же, как в реале.
То есть, если они каждые 30 секунд снимаются, то и в модели узел движется
от точки до точки 30 сек.

С уважением, Привалов А.Ю.

2 ноября 2016 г., 11:11 пользователь Al-xandr1 notifications@github.com
написал:

**Comment by Al-xandr1** [comment]
**DONE in** 71eff5a7c05d1e00ff74246bf1230005f5d2a250
