### ISSUE TITLE
Счётчик домашнего маршрута при хождении по локациям зануляется

### ISSUE THREAD

**Issue by Al-xandr1** [Al-xandr1/DTNResearch#47]
В процессе хождения по локациям счётчики локаций уменьшаются. У домашней локации счётчик не должен уменьшаться меньше единицы (вроде как). А он уменьшается... Это проблема?

**Comment by privalov1967** [comment]
Счётчик у домашней локации не должен уменьшаться меньше единицы, когда идёт
создание нового маршрута из эталонного в начале дня. После этого этот
счётчик ведёт себя также, как остальные счётчики, и в конце маршрута тоже
должен быть нулём. Уход домой после окончания маршрута не считается
посещением локации, и на счётчик не воздействует. А вот на следующий день,
когда будет сделан новый маршрут, и узел покинет первую (домашнюю) локацию,
счётчик уменьшится. Именно поэтому при формировании этого маршрута счётчик
не должен быть меньше единицы.

С уважением, Привалов А.Ю.

17 ноября 2016 г., 17:52 пользователь Al-xandr1 notifications@github.com
написал:
